version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: bank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Test@123"
      MYSQL_DATABASE: "bankappdb"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - bank-net

  backend:
    image: java:latest            # <-- your built image name
    container_name: bankapp
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
    ports:
      - "8080:8080"
    restart: always
    networks:
      - bank-net

volumes:
  mysql-data:

networks:
  bank-net:
    driver: bridge