name: TestingAllWorkFlows
run-name: TestingAllWorkFlows

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      github_sha: ${{steps.step1.output.sha}}
    steps:
  
      - name: sample
        id: step1
        run: |
              echo "sha=${{github.sha}}" >>GITHUB_OUTPUT
              echo ${{github.ref_name}}
        
