name: TestingAllWorkFlows
run-name: TestingAllWorkFlows

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: sample
        run: |
              echo ${{github.sha}}
              echo ${{github.ref_name}}
        
